### ISSUE TITLE
Data too long for column 'JOB_DATA'

### ISSUE THREAD

**Issue by vbonamy** [EsupPortail/esup-smsu-api#10]
Bonjour,

Un envoi de SMS à un groupe de 3226 numéros de téléphone échoue au niveau d'esup-smsu-api avec le message d'erreur ci-dessous.

Le même message envoyé à 'seulement' 1612 numéros fonctionne.

De ce qu'on comprend :
* la sérialisation et insertion du JOB_DATA initiée par org.esupportail.smsuapi.services.scheduler.SchedulerUtils.java:73 dans la table MySQL Quartz échoue car on dépasse la taille max du BLOB MySQL 
* la colonne  JOB_DATA de la table QRTZ_JOB_DETAILS est un BLOB ; sous MySQL ça correspond à 64 KB.
https://stackoverflow.com/questions/5775571/what-is-the-maximum-length-of-data-i-can-put-in-a-blob-column-in-mysql
* a priori il suffirait de déclarer JOB_DATA non pas comme un BLOB (64 KB) mais comme un MEDIUMBLOB (16 MB) voir un LONGBLOB (4GB) ?

Changement à faire dans 
src/main/resources/database/create_qrtz_tables_esup-smsuapi.sql ?

Merci.
Vincent.

<pre>
org.quartz.JobPersistenceException: Couldn't store job: Data truncation: Data too long for column 'JOB_DATA' at row 1 [See nested exception: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'JOB_DATA' at row 1]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeJob(JobStoreSupport.java:857)
	at org.quartz.impl.jdbcjobstore.JobStoreTX.storeJobAndTrigger(JobStoreTX.java:167)
	at org.quartz.core.QuartzScheduler.scheduleJob(QuartzScheduler.java:613)
	at org.quartz.impl.StdScheduler.scheduleJob(StdScheduler.java:238)
	at org.esupportail.smsuapi.services.scheduler.SchedulerUtils.launchSuperviseSmsSending(SchedulerUtils.java:73)
	at org.esupportail.smsuapi.business.SendSmsManager.sendSMS(SendSmsManager.java:108)
	at org.esupportail.smsuapi.services.servlet.RestServletActions.sendSMS(RestServletActions.java:46)
	at org.esupportail.smsuapi.services.servlet.RestServletActions.wsActionSendSms(RestServletActions.java:29)
</pre>

**Comment by vbonamy** [comment]
Bonjour,
Pour permettre à smsu d'envoyer des messages à un nombre important de numéros téléphones en une fois, je propose de modifier l'ensemble des BLOB utilisés par SMSU (au travers de Quartz) pour les placer en MEDIUMBLOB.
C'est ce que j'ai fait sur notre instance SMSU / SMSU-API ici, ça fonctionne bien.
Merci,
Vincent.

<pre>
use smsuapi
ALTER TABLE QRTZ_TRIGGERS MODIFY JOB_DATA MEDIUMBLOB;
ALTER TABLE QRTZ_BLOB_TRIGGERS MODIFY BLOB_DATA MEDIUMBLOB;
ALTER TABLE QRTZ_CALENDARS MODIFY CALENDAR MEDIUMBLOB;

use smsu
ALTER TABLE QRTZ_JOB_DETAILS MODIFY JOB_DATA MEDIUMBLOB;
ALTER TABLE QRTZ_BLOB_TRIGGERS MODIFY BLOB_DATA MEDIUMBLOB;
ALTER TABLE QRTZ_CALENDARS MODIFY CALENDAR MEDIUMBLOB;
</pre>
