### ISSUE TITLE
enhance allmysms error handing

### ISSUE THREAD

**Issue by prigaux** [EsupPortail/esup-smsu-api#6]
2017-02-18 09:26:21,709 ERROR org.esupportail.smsuapi.services.sms.impl.allmysms.SMSSenderAllmysms - SMSSenderAllmysms.java:77   - An error occurs sending SMS :  - id : 148
546 - recipient : 06xxxxx - message : xxxx
org.springframework.http.converter.HttpMessageNotReadableException: Could not read JSON: Unexpected character ('S' (code 83)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@747f23da; line: 1, column: 2]; nested exception is org.codehaus.jackson.JsonParseException: Unexpected character ('S' (code 83)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@747f23da; line: 1, column: 2]
        at org.springframework.http.converter.json.MappingJacksonHttpMessageConverter.readJavaType(MappingJacksonHttpMessageConverter.java:169)
        at org.springframework.http.converter.json.MappingJacksonHttpMessageConverter.read(MappingJacksonHttpMessageConverter.java:161)
        at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:94)
        at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:693)
        at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:679)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:496)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:452)
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:400)
        at org.esupportail.smsuapi.services.sms.impl.allmysms.SMSSenderAllmysms.sendMessage(SMSSenderAllmysms.java:70)
        at org.esupportail.smsuapi.business.SendSmsManager.sendWaitingForSendingSms(SendSmsManager.java:206)
        at org.esupportail.smsuapi.services.scheduler.job.SuperviseSmsSending.executeJob(SuperviseSmsSending.java:47)
        at org.esupportail.smsuapi.services.scheduler.AbstractQuartzJob.executeInternal(AbstractQuartzJob.java:96)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:203)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:520)
Caused by: org.codehaus.jackson.JsonParseException: Unexpected character ('S' (code 83)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@747f23da; line: 1, column: 2]
        at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1433)
        at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:521)
        at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:442)
        at org.codehaus.jackson.impl.Utf8StreamParser._handleUnexpectedValue(Utf8StreamParser.java:2090)
        at org.codehaus.jackson.impl.Utf8StreamParser._nextTokenNotInObject(Utf8StreamParser.java:606)
        at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:492)
        at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2770)
        at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2718)
        at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1923)
        at org.springframework.http.converter.json.MappingJacksonHttpMessageConverter.readJavaType(MappingJacksonHttpMessageConverter.java:166)
        ... 14 more

**Comment by prigaux** [comment]
The pb is allmysms returning the following string:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'ece710a7926eff6b814768b06145a9f2' for key 'uniqueSignature'{"status":114,"statusText":"Request already submitted"}

which is clearly a concat of an internal error message + valid json

**Comment by prigaux** [comment]
Fixed by allmysms. So not changing anything in smsu-api
